#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
gen_regs.py — aurora 寄存器映射生成器 (单一真源).

读 tools/aurora_regs.json 生成:
  src/aurora_addr_def.vh            (Verilog 地址定义)
  include/aurora_regs.h             (C 头)
  src/regs/aurora_<block>_regs.v    (每块一个自命中寄存器从器)

用法: python3 tools/gen_regs.py [--check]
注: aurora_regbank.v 与 aurora_top.v 已转手写固定, 不在本生成器产出.
    regs.tmpl 为可选输入模板(手写, 与 JSON 平级), 本实现直接用 Python 拼接,
    等价于模板, 故不强制引用 regs.tmpl.
"""
import argparse
import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
PROJ = os.path.dirname(HERE)
JSON_PATH = os.path.join(HERE, "aurora_regs.json")
VH_OUT = os.path.join(PROJ, "src", "aurora_addr_def.vh")
H_OUT = os.path.join(PROJ, "include", "aurora_regs.h")
REGS_OUT = os.path.join(PROJ, "src", "regs", "aurora_{}_regs.v")


def entry_int(hexstr, what):
    try:
        return int(hexstr, 0)
    except (TypeError, ValueError):
        raise ValueError("%s: 无法解析的十六进制值 '%s'" % (what, hexstr))


def gen(data):
    base = entry_int(data["base"], "base")
    win = entry_int(data["size"], "size")
    version = entry_int(data["version"], "version")
    name = data["name"].lower()
    blocks_info = []
    for bname, blk in data["blocks"].items():
        bbase = entry_int(blk["base"], "block %s.base" % bname)
        bsize = entry_int(blk["size"], "block %s.size" % bname)
        reserved = bool(blk.get("reserved", False))
        regs = []
        for r in blk["regs"]:
            goff = bbase + entry_int(r["offset"], "%s.%s.offset" % (bname, r["name"]))
            access = "ro" if "ro" in r else "rw"
            rst = entry_int(r.get("rst", "0x0"), "%s.%s.rst" % (bname, r["name"]))
            autoclear = bool(r.get("autoclear", False))
            in_flag = None
            if "in" in r:
                in_flag = bool(r["in"])
            regs.append(dict(name=r["name"], goff=goff, access=access, rst=rst,
                             desc=r.get("desc", ""), autoclear=autoclear,
                             in_flag=in_flag))
        blocks_info.append(dict(bname=bname, u=bname.upper(), base=bbase,
                                size=bsize, reserved=reserved, regs=regs))
    for b in blocks_info:
        assert b["base"] >= 0 and b["base"] < win, b
    assert win <= 1 << 16, "window 超出 16bit P-BUS 地址域"
    return name, base, win, version, blocks_info


def write_headers(name, base, win, version, blocks_info):
    """生成 .vh 与 .h(地址常量, 不含任何从器逻辑)."""
    os.makedirs(os.path.dirname(VH_OUT), exist_ok=True)
    L = ["// AUTO-GENERATED by tools/gen_regs.py — 勿手工修改.",
         "// 单一真源: tools/aurora_regs.json (%s)" % name,
         "`ifndef AURORA_ADDR_DEF_INC",
         "`define AURORA_ADDR_DEF_INC",
         "//---- P-BUS 场窗 ----"]
    L.append("`define AURORA_BASE     32'h%08X" % base)
    L.append("`define AURORA_WINDOW   32'h%08X" % win)
    L.append("`define AURORA_VERSION  32'h%08X" % version)
    for b in blocks_info:
        L.append("//---- %s ----" % b["bname"])
        L.append("`define AURORA_%s_BASE 32'h%08X" % (b["u"], b["base"]))
        L.append("`define AURORA_%s_SIZE 32'h%08X" % (b["u"], b["size"]))
        for r in b["regs"]:
            L.append("`define AURORA_%s_%s     32'h%08X   // %s %s"
                     % (b["u"], r["name"].upper(), r["goff"], r["access"], r["desc"]))
            L.append("`define AURORA_%s_%s_RST 32'h%08X   // %s 复位值"
                     % (b["u"], r["name"].upper(), r["rst"], r["access"]))
    L.append("`endif // AURORA_ADDR_DEF_INC")
    with open(VH_OUT, "w", encoding="utf-8") as f:
        f.write("\n".join(L) + "\n")

    os.makedirs(os.path.dirname(H_OUT), exist_ok=True)
    C = ["/* AUTO-GENERATED by tools/gen_regs.py — 勿手工修改. */",
         "/* 单一真源: tools/aurora_regs.json (%s) */" % name,
         "#ifndef AURORA_REGS_H",
         "#define AURORA_REGS_H", "",
         "#define AURORA_BASE        0x%08X    /* 窗内绝对基址 */" % base,
         "#define AURORA_WINDOW_SIZE 0x%08Xu    /* 单窗口映射尺寸 */" % win,
         "#define AURORA_VERSION     0x%08Xu" % version, ""]
    for b in blocks_info:
        C.append("/*---- %s ----*/" % b["bname"])
        C.append("#define AURORA_%s_BASE 0x%04Xu" % (b["u"], b["base"]))
        C.append("#define AURORA_%s_SIZE 0x%04Xu" % (b["u"], b["size"]))
        for r in b["regs"]:
            C.append("#define AURORA_%s_%s    0x%04Xu  /* %s: %s */"
                     % (b["u"], r["name"].upper(), r["goff"], r["access"], r["desc"]))
            C.append("#define AURORA_%s_%s_RST 0x%08Xu  /* %s: 复位值 */"
                     % (b["u"], r["name"].upper(), r["rst"], r["access"]))
    C.append("")
    C.append("#endif /* AURORA_REGS_H */")
    with open(H_OUT, "w", encoding="utf-8") as f:
        f.write("\n".join(C) + "\n")
    return [VH_OUT, H_OUT]

def write_block(blk, version):
    """生成 src/regs/aurora_<block>_regs.v: 自命中 P-BUS 从器.

    接口(读写分开, 按 AXI 先后):
      in  : aclk aresetn p_wvalid p_waddr[15:0] p_wdata[31:0]
            p_wstrb[3:0] p_rvalid p_raddr[15:0]
      out : o_rvalid o_rdata[31:0]  及业务 o_<rw>... / i_<ro_in>...
    命中用 `AURORA_<U>_BASE/SIZE 窗口判定, 不依赖任何 p_sel.
    """
    path = REGS_OUT.format(blk["bname"])
    b = blk
    U = b["u"]
    base_expr = "`AURORA_%s_BASE" % U
    win_expr = "(`AURORA_%s_BASE + `AURORA_%s_SIZE)" % (U, U)

    # ---- reserved: 占位假从器, 永不命中 ----
    if b["reserved"]:
        L = ["`timescale 1ns / 1ps",
             "// AUTO-GENERATED by tools/gen_regs.py. 保留块(reserved): 写忽略, 读恒 0(地址占位).",
             "module aurora_%s_regs (" % b["bname"],
             "    input  wire aclk",
             "    ,input  wire aresetn",
             "    ,input  wire p_wvalid, input  wire [15:0] p_waddr",
             "    ,input  wire [31:0] p_wdata, input  wire [3:0] p_wstrb",
             "    ,input  wire p_rvalid, input  wire [15:0] p_raddr",
             "    ,output wire o_rvalid, output wire [31:0] o_rdata",
             ");",
             "    // 占位从器: 永不命中, 读/写皆无副作用.",
             "    assign o_rvalid = 1'b0;",
             "    assign o_rdata  = 32'd0;",
             "endmodule"]
        with open(path, "w", encoding="utf-8") as f:
            f.write("\n".join(L) + "\n")
        return path

    rws = [r for r in b["regs"] if r["access"] == "rw"]
    ros = [r for r in b["regs"] if r["access"] == "ro"]
    ros_in = [r for r in ros if r["in_flag"] is not False]   # 外设输入
    ros_cst = [r for r in ros if r["in_flag"] is False]      # 固定常数
    any_ac = any(r["autoclear"] for r in rws)

    L = ["`timescale 1ns / 1ps",
         "// AUTO-GENERATED by tools/gen_regs.py. 本模块 = 该块寄存器的自命中 P-BUS 从.",
         "// regbank 为手写纯 AXI 从+广播; 本从器对读写按 AXI 先后自命中(窗口=BASE/SIZE).",
         "// 业务逻辑在外设模块(如 aurora_led.v)用 o_*/i_* 接口.",
         '`include "aurora_addr_def.vh"',
         "module aurora_%s_regs (" % b["bname"],
         "    input  wire aclk",
         "    ,input  wire aresetn",
         "    ,input  wire p_wvalid",
         "    ,input  wire [15:0] p_waddr",
         "    ,input  wire [31:0] p_wdata",
         "    ,input  wire [3:0]  p_wstrb",
         "    ,input  wire p_rvalid",
         "    ,input  wire [15:0] p_raddr",
         "    ,output wire o_rvalid",
         "    ,output wire [31:0] o_rdata"]
    for r in rws:
        L.append("    ,output wire [31:0] o_%s" % r["name"])
    for r in ros_in:
        L.append("    ,input  wire [31:0] i_%s" % r["name"])
    L.append(");")
    L.append("")
    L.append("    // ---- 可写寄存器 ----")
    for r in rws:
        L.append("    reg [31:0] r_%s;" % r["name"])
    L.append("")
    L.append("    // ---- 写: 自命中(p_wvalid = bank 写握手拍, 一拍广播) ----")
    L.append("    wire hit_w = p_wvalid & (p_waddr >= %s) & (p_waddr < %s);"
             % (base_expr, win_expr))
    L.append("    always @(posedge aclk or negedge aresetn) begin")
    L.append("        if (~aresetn) begin")
    for r in rws:
        L.append("            r_%s <= `AURORA_%s_%s_RST;" % (r["name"], U, r["name"].upper()))
    L.append("        end else begin")
    if any_ac:
        for r in rws:
            if r["autoclear"]:
                L.append("            r_%s <= {r_%s[31:1], 1'b0};   // autoclear: bit0 每拍自动清"
                         % (r["name"], r["name"]))
    L.append("            if (hit_w) begin")
    L.append("                case (p_waddr)")
    for r in rws:
        tag = "   // (autoclear 写覆盖)" if r["autoclear"] else ""
        L.append("                    `AURORA_%s_%s: r_%s <= p_wdata;%s"
                 % (U, r["name"].upper(), r["name"], tag))
    L.append("                    default: ;")
    L.append("                endcase")
    L.append("            end")
    L.append("        end")
    L.append("    end")
    L.append("")
    L.append("    // ---- 读返回: 组合译码 ----")
    L.append("    reg [31:0] rd_val;")
    L.append("    always @(*) begin")
    L.append("        case (p_raddr)")
    for r in rws:
        L.append("            `AURORA_%s_%s: rd_val = r_%s;"
                 % (U, r["name"].upper(), r["name"]))
    for r in ros_in:
        L.append("            `AURORA_%s_%s: rd_val = i_%s;"
                 % (U, r["name"].upper(), r["name"]))
    for r in ros_cst:
        val = version if r["name"] == "version" else 0
        L.append("            `AURORA_%s_%s: rd_val = 32'h%08X; // 固定常数"
                 % (U, r["name"].upper(), val))
    L.append("            default: rd_val = 32'd0;")
    L.append("        endcase")
    L.append("    end")
    L.append("")
    L.append("    // ---- 读: 按地址自命中 ----")
    L.append("    wire addr_hit = (p_raddr >= %s) & (p_raddr < %s);" % (base_expr, win_expr))
    L.append("    assign o_rvalid = p_rvalid & addr_hit;   // 握手拍才声明命中(供 top 隔离互检/多命中防护显式使用)")
    L.append("    assign o_rdata  = addr_hit ? rd_val : 32'd0;   // 恒为按地址译码; top 用 OR 归并成单根 p_rdata")
    L.append("")
    L.append("    // ---- 输出/输入绑定(供外设业务) ----")
    for r in rws:
        L.append("    assign o_%s = r_%s;" % (r["name"], r["name"]))
    if rws:
        L.append("")
    L.append("endmodule")
    with open(path, "w", encoding="utf-8") as f:
        f.write("\n".join(L) + "\n")
    return path

def main(argv=None):
    ap = argparse.ArgumentParser(description="aurora 寄存器生成器")
    ap.add_argument("--check", action="store_true",
                    help="重新生成并比对现有文件, 任何差异以非零码退出")
    a = ap.parse_args(argv)

    with open(JSON_PATH, "r", encoding="utf-8") as f:
        data = json.load(f)
    name, base, win, version, blocks_info = gen(data)

    # 记录 生成前/后 文件内容, 用于 --check idempotence
    def snapshot():
        s = {}
        for blk in blocks_info:
            p = REGS_OUT.format(blk["bname"])
            s[p] = open(p, "r", encoding="utf-8").read() if os.path.exists(p) else None
        for p in (VH_OUT, H_OUT):
            s[p] = open(p, "r", encoding="utf-8").read() if os.path.exists(p) else None
        return s

    before = snapshot()
    written = write_headers(name, base, win, version, blocks_info)
    for blk in blocks_info:
        written.append(write_block(blk, version))
    after = snapshot()

    if not a.check:
        print("generated:")
        for p in written:
            print("  " + p)
        return 0

    diffs = [p for p in after if before[p] != after[p]]
    if diffs:
        print("--check 失败: 以下输出已过期(请先运行本脚本提交生成物):")
        for p in diffs:
            print("  " + p)
        return 1
    print("--check ok: 全部输出与真源一致(幂等).")
    return 0


if __name__ == "__main__":
    sys.exit(main())