// AUTO-GENERATED by tools/gen_regs.py — 勿手工修改.
// 单一真源: tools/aurora_regs.json (aurora)
`ifndef AURORA_ADDR_DEF_INC
`define AURORA_ADDR_DEF_INC
//---- P-BUS 场窗 ----
`define AURORA_BASE     32'h40000000
`define AURORA_WINDOW   32'h00010000
`define AURORA_VERSION  32'h01001A00
//---- system ----
`define AURORA_SYSTEM_BASE 32'h00000000
`define AURORA_SYSTEM_SIZE 32'h00000010
`define AURORA_SYSTEM_SCRATCH     32'h00000000   // rw 通用读写测试寄存器, 任意值
`define AURORA_SYSTEM_SCRATCH_RST 32'h00000000   // rw 复位值
`define AURORA_SYSTEM_VERSION     32'h00000004   // ro 固件版本 (只读, 取 JSON version)
`define AURORA_SYSTEM_VERSION_RST 32'h00000001   // ro 复位值
`define AURORA_SYSTEM_CTRL     32'h00000008   // rw bit0=软件复位(置1后自动清), 其余保留
`define AURORA_SYSTEM_CTRL_RST 32'h00000000   // rw 复位值
//---- led ----
`define AURORA_LED_BASE 32'h00000010
`define AURORA_LED_SIZE 32'h00000010
`define AURORA_LED_VALUE     32'h00000010   // rw LED 点亮模式与控制值 [3:0]; 位0->LED0 ... 位3->LED3 (高电平点亮) (默认全灭)
`define AURORA_LED_VALUE_RST 32'h00000000   // rw 复位值
`define AURORA_LED_CTRL     32'h00000014   // rw bit0=LED 使能 (0:LED 全灭; 1:按 value 点亮)
`define AURORA_LED_CTRL_RST 32'h00000000   // rw 复位值
`define AURORA_LED_STATUS     32'h00000018   // ro 只读状态: [31:9]保留 [4]使能 [3:0]实际 LED 输出
`define AURORA_LED_STATUS_RST 32'h00000000   // ro 复位值
//---- adc ----
`define AURORA_ADC_BASE 32'h00000020
`define AURORA_ADC_SIZE 32'h00000010
`define AURORA_ADC_CTRL     32'h00000020   // rw 预留: 转换控制
`define AURORA_ADC_CTRL_RST 32'h00000000   // rw 复位值
`define AURORA_ADC_STATUS     32'h00000024   // ro 预留: 忙/就绪状态
`define AURORA_ADC_STATUS_RST 32'h00000000   // ro 复位值
`define AURORA_ADC_DATA     32'h00000028   // ro 预留: 采样数据
`define AURORA_ADC_DATA_RST 32'h00000000   // ro 复位值
//---- dma ----
`define AURORA_DMA_BASE 32'h00000030
`define AURORA_DMA_SIZE 32'h00000010
`define AURORA_DMA_CTRL     32'h00000030   // rw bit0=RUN(写1启动假数据源发一帧, 自动清) 其余保留
`define AURORA_DMA_CTRL_RST 32'h00000000   // rw 复位值
`define AURORA_DMA_LEN     32'h00000034   // rw 每帧字数(32bit 字, 默认1024); 与 PS 侧 DMA BTT(=len*4) 保持一致
`define AURORA_DMA_LEN_RST 32'h00000400   // rw 复位值
`define AURORA_DMA_STATUS     32'h00000038   // ro [0]busy [1]帧结束(新RUN清) [15:8]已发帧数(回绕)
`define AURORA_DMA_STATUS_RST 32'h00000000   // ro 复位值
`endif // AURORA_ADDR_DEF_INC
