/* AUTO-GENERATED by tools/gen_regs.py — 勿手工修改. */
/* 单一真源: tools/aurora_regs.json (aurora) */
#ifndef AURORA_REGS_H
#define AURORA_REGS_H

#define AURORA_BASE        0x40000000    /* 窗内绝对基址 */
#define AURORA_WINDOW_SIZE 0x00010000u    /* 单窗口映射尺寸 */
#define AURORA_VERSION     0x01001A00u

/*---- system ----*/
#define AURORA_SYSTEM_BASE 0x0000u
#define AURORA_SYSTEM_SIZE 0x0010u
#define AURORA_SYSTEM_SCRATCH    0x0000u  /* rw: 通用读写测试寄存器, 任意值 */
#define AURORA_SYSTEM_SCRATCH_RST 0x00000000u  /* rw: 复位值 */
#define AURORA_SYSTEM_VERSION    0x0004u  /* ro: 固件版本 (只读, 取 JSON version) */
#define AURORA_SYSTEM_VERSION_RST 0x00000001u  /* ro: 复位值 */
#define AURORA_SYSTEM_CTRL    0x0008u  /* rw: bit0=软件复位(置1后自动清), 其余保留 */
#define AURORA_SYSTEM_CTRL_RST 0x00000000u  /* rw: 复位值 */
/*---- led ----*/
#define AURORA_LED_BASE 0x0010u
#define AURORA_LED_SIZE 0x0010u
#define AURORA_LED_VALUE    0x0010u  /* rw: LED 点亮模式与控制值 [3:0]; 位0->LED0 ... 位3->LED3 (高电平点亮) (默认全灭) */
#define AURORA_LED_VALUE_RST 0x00000000u  /* rw: 复位值 */
#define AURORA_LED_CTRL    0x0014u  /* rw: bit0=LED 使能 (0:LED 全灭; 1:按 value 点亮) */
#define AURORA_LED_CTRL_RST 0x00000000u  /* rw: 复位值 */
#define AURORA_LED_STATUS    0x0018u  /* ro: 只读状态: [31:9]保留 [4]使能 [3:0]实际 LED 输出 */
#define AURORA_LED_STATUS_RST 0x00000000u  /* ro: 复位值 */
/*---- adc ----*/
#define AURORA_ADC_BASE 0x0020u
#define AURORA_ADC_SIZE 0x0010u
#define AURORA_ADC_CTRL    0x0020u  /* rw: 预留: 转换控制 */
#define AURORA_ADC_CTRL_RST 0x00000000u  /* rw: 复位值 */
#define AURORA_ADC_STATUS    0x0024u  /* ro: 预留: 忙/就绪状态 */
#define AURORA_ADC_STATUS_RST 0x00000000u  /* ro: 复位值 */
#define AURORA_ADC_DATA    0x0028u  /* ro: 预留: 采样数据 */
#define AURORA_ADC_DATA_RST 0x00000000u  /* ro: 复位值 */
/*---- dma ----*/
#define AURORA_DMA_BASE 0x0030u
#define AURORA_DMA_SIZE 0x0010u
#define AURORA_DMA_CTRL    0x0030u  /* rw: bit0=RUN(写1启动假数据源发一帧, 自动清) 其余保留 */
#define AURORA_DMA_CTRL_RST 0x00000000u  /* rw: 复位值 */
#define AURORA_DMA_LEN    0x0034u  /* rw: 每帧字数(32bit 字, 默认1024); 与 PS 侧 DMA BTT(=len*4) 保持一致 */
#define AURORA_DMA_LEN_RST 0x00000400u  /* rw: 复位值 */
#define AURORA_DMA_STATUS    0x0038u  /* ro: [0]busy [1]帧结束(新RUN清) [15:8]已发帧数(回绕) */
#define AURORA_DMA_STATUS_RST 0x00000000u  /* ro: 复位值 */

#endif /* AURORA_REGS_H */
