`timescale 1ns / 1ps
// AUTO-GENERATED by tools/gen_regs.py. 本模块 = 该块寄存器的自命中 P-BUS 从.
// regbank 为手写纯 AXI 从+广播; 本从器对读写按 AXI 先后自命中(窗口=BASE/SIZE).
// 业务逻辑在外设模块(如 aurora_led.v)用 o_*/i_* 接口.
`include "aurora_addr_def.vh"
module aurora_dma_regs (
    input  wire aclk
    ,input  wire aresetn
    ,input  wire p_wvalid
    ,input  wire [15:0] p_waddr
    ,input  wire [31:0] p_wdata
    ,input  wire [3:0]  p_wstrb
    ,input  wire p_rvalid
    ,input  wire [15:0] p_raddr
    ,output wire o_rvalid
    ,output wire [31:0] o_rdata
    ,output wire [31:0] o_ctrl
    ,output wire [31:0] o_len
    ,input  wire [31:0] i_status
);

    // ---- 可写寄存器 ----
    reg [31:0] r_ctrl;
    reg [31:0] r_len;

    // ---- 写: 自命中(p_wvalid = bank 写握手拍, 一拍广播) ----
    wire hit_w = p_wvalid & (p_waddr >= `AURORA_DMA_BASE) & (p_waddr < (`AURORA_DMA_BASE + `AURORA_DMA_SIZE));
    always @(posedge aclk or negedge aresetn) begin
        if (~aresetn) begin
            r_ctrl <= `AURORA_DMA_CTRL_RST;
            r_len <= `AURORA_DMA_LEN_RST;
        end else begin
            r_ctrl <= {r_ctrl[31:1], 1'b0};   // autoclear: bit0 每拍自动清
            if (hit_w) begin
                case (p_waddr)
                    `AURORA_DMA_CTRL: r_ctrl <= p_wdata;   // (autoclear 写覆盖)
                    `AURORA_DMA_LEN: r_len <= p_wdata;
                    default: ;
                endcase
            end
        end
    end

    // ---- 读返回: 组合译码 ----
    reg [31:0] rd_val;
    always @(*) begin
        case (p_raddr)
            `AURORA_DMA_CTRL: rd_val = r_ctrl;
            `AURORA_DMA_LEN: rd_val = r_len;
            `AURORA_DMA_STATUS: rd_val = i_status;
            default: rd_val = 32'd0;
        endcase
    end

    // ---- 读: 按地址自命中 ----
    wire addr_hit = (p_raddr >= `AURORA_DMA_BASE) & (p_raddr < (`AURORA_DMA_BASE + `AURORA_DMA_SIZE));
    assign o_rvalid = p_rvalid & addr_hit;   // 握手拍才声明命中(供 top 隔离互检/多命中防护显式使用)
    assign o_rdata  = addr_hit ? rd_val : 32'd0;   // 恒为按地址译码; top 用 OR 归并成单根 p_rdata

    // ---- 输出/输入绑定(供外设业务) ----
    assign o_ctrl = r_ctrl;
    assign o_len = r_len;

endmodule
