`timescale 1ns / 1ps
// AUTO-GENERATED by tools/gen_regs.py. 保留块(reserved): 写忽略, 读恒 0(地址占位).
module aurora_adc_regs (
    input  wire aclk
    ,input  wire aresetn
    ,input  wire p_wvalid, input  wire [15:0] p_waddr
    ,input  wire [31:0] p_wdata, input  wire [3:0] p_wstrb
    ,input  wire p_rvalid, input  wire [15:0] p_raddr
    ,output wire o_rvalid, output wire [31:0] o_rdata
);
    // 占位从器: 永不命中, 读/写皆无副作用.
    assign o_rvalid = 1'b0;
    assign o_rdata  = 32'd0;
endmodule
